#:schema https://raw.githubusercontent.com/git-town/git-town/refs/heads/main/docs/git-town.schema.json

# See https://www.git-town.com/configuration-file for details

[branches]
main = "master"
order = "asc"
unknown-type = "feature"

[create]
share-new-branches = "no"
stash = true

[propose]
breadcrumb = "branches"
breadcrumb-direction = "down"

[ship]
delete-tracking-branch = true
ignore-uncommitted = true
strategy = "api"

[sync]
auto-sync = true
detached = false
feature-strategy = "rebase"
perennial-strategy = "rebase"
prototype-strategy = "rebase"
push-branches = true
push-hook = true
tags = true
upstream = true
