name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.24.0
      name: Spellcheck
      with:
        output_file: spellcheck-output.txt
    - run: cat spellcheck-output.txt >> $GITHUB_STEP_SUMMARY
    - uses: actions/github-script@v3
      with:
        script: |
          const { readFileSync } = require('fs');
          const lines = readFileSync('spellcheck-output.txt').toString().split('\n');
          while (lines.length) {
            const line = lines.unshift();
            if (line === 'Misspelled words:') {
              const filename = lines.unshift();
              console.log(`::notice file=${filename},title=Spelling errors::{message}`);
            }
          }
