name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: rojopolis/spellcheck-github-actions@0.28.0
      name: Spellcheck
      with:
        output_file: spellcheck-output.txt
    - uses: actions/github-script@v7
      with:
        script: |
          const files = {};
          const { readFileSync } = require('fs');
          const lines = readFileSync('spellcheck-output.txt').toString().split('\n');
          while (lines.length > 0) {
            let line = lines.shift();
            if (line === 'Misspelled words:') {
              const filename = lines.shift().split('> ')[1].split(': ')[0];

              let words;
              if (filename in files) {
                words = files[filename];
              } else words = files[filename] = [];

              const delim = lines.shift();
              while (true) {
                line = lines.shift(); 
                if (line === delim) break;
                words.push(line);
              }
            }
          }
          for (const [filename, words] of Object.entries(files)) {
            console.log(`::notice file=${filename},title=Spelling errors::${words.join(', ')}`);
          }
